modLoader="javafml"
loaderVersion="[47,)"
license="The Apache License, Version 2.0"
issueTrackerURL="https://github.com/MelanX/PackEssentials/issues"

[[mods]]
modId="packessentials"
version="${version}"
displayName="Pack Essentials"
displayURL = "https://melanx.github.io/Mod-Wikis/"
updateJSONURL="https://assets.melanx.de/updates/pack-essentials.json"
authors="MelanX"
description='''
A universal mod for all my modpacks. Can be configured to load only required things in each modpack.
'''

[[dependencies.packessentials]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.packessentials]]
    modId="forge"
    mandatory=true
    versionRange="[${forge},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.packessentials]]
    modId="libx"
    mandatory=true
    versionRange="[1.20.1-5.0.14,)"
    ordering="NONE"
    side="BOTH"
